### ISSUE TITLE
天気情報を取得

### ISSUE THREAD

**Issue by harusys** [harusys/newsh#13]
### Todo List

- [x] Function リソース作成（Python）
- [x] newsh API に HTTP Trigger 追加　→#22 で対応
- [x] newsh 天気情報 API に HTTP Trigger 追加
- [x] 検索条件（例：地域？市？区？、時間）を何にできて、何にするか検討　→追加を #31, #32 で実装
- [x] 実装（天気情報を取得）

**Comment by hrtk7623** [comment]
【メモ】
VScode上ではLocal Project（Azureにデプロイされるディレクトリ）は，関数リソース別にディレクトリ作成した方がよさそう．  
一緒にしてしまうと，「host.json」や「setting.json」が共通ファイルになってしまうため上書きがおこる（？）
