### ISSUE TITLE
通知時刻をユーザ毎に設定可能とする

### ISSUE THREAD

**Issue by harusys** [harusys/newsh#23]
### Purpose

通知時刻が全ユーザ 10:00 / 21:00 固定となっているが、ユーザ毎に設定可能とする

### Todo list

- [ ] DB 構築　　※Cosmos DB（NoSQL）
- [ ] 設定画面の構築　　※Static Web App
- [ ] gateway から DB 参照

**Comment by harusys** [comment]
React+TypeScript+ESLint+Prettierをまとめて環境構築
https://zenn.dev/jpn_asane/articles/d7f44682b74fdc

**Comment by harusys** [comment]
Material UI v5
https://mui.com/getting-started/installation/

こんにちはMUI！ 新しくなったMaterial UI v5
https://zenn.dev/h_yoshikawa0724/articles/2021-09-26-material-ui-v5

**Comment by harusys** [comment]
6. React クライアント アプリを Azure Function API に接続する
https://docs.microsoft.com/ja-jp/azure/developer/javascript/how-to/with-web-app/static-web-app-with-swa-cli/connect-client-to-api

**Comment by harusys** [comment]
Material Table → Material Table / Core
https://material-table-core.com/docs/
