### ISSUE TITLE
Python の Formatter 導入

### ISSUE THREAD

**Issue by harusys** [harusys/newsh#27]
### Purpose

Python の Formatter を導入する

### Todo list

- [x] 導入する Formatter / Linter を決める　→　Linter: flake8, Formatter: black を選定（コメントの外部リンク参照）
- [x] 自動設定されるように設定ファイルを追加する　→　settings.json で自動設定を追加
- [x] CI で自動チェックするよう追加　→　GitHub Actions で push / pull-request 時にチェックを追加

**Comment by harusys** [comment]
Pythonのコードフォーマッターについての個人的ベストプラクティス
https://qiita.com/sin9270/items/85e2dab4c0144c79987d

**Comment by harusys** [comment]
GitHub Actionsを使って、Pythonのコードをプッシュするたびにflake8でチェックする
https://yoshikiito.net/blog/archives/python-github-actions-flake8/
