### ISSUE TITLE
リッチメニューを GitHub Action からリリース

### ISSUE THREAD

**Issue by harusys** [harusys/newsh#36]
### Purpose

LINE リッチメニューを GitHub Action からリリースできるようにする

Messaging API を活用すれば、LINE Developer 開かなくても GitHub Actions からリリース可能なはず
https://developers.line.biz/ja/docs/messaging-api/using-rich-menus/#creating-a-rich-menu-using-the-messaging-api

### Todo list

- [ ] GitHub Action 定義追加
- [ ] リッチメニューサイズなども GitHub 側で設定可能なようにする
- [ ] アップロードする画像がサイズ違いなら、アップロード前にチェックしておく（できれば）
